version: "2"
services:
  application:
    image: ${IMAGE_IMAGE}
    container_name: sensor
    ports:
      - "8080:8080"
    environment:
      - AWS_ACESS_KEY_ID=${AWS_ACESS_KEY_ID}
      - AWS_SECRET_ACESS_KEY=${AWS_SECRET_ACESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - BUCKET_NAME = ${BUCKET_NAME}


    